# QUERIES CONSTANTS THAT ARE USED A LOT

CREATE_TABLE_EMAILS = """CREATE TABLE emails ( 
	id INT NOT NULL AUTO_INCREMENT, 
    email VARCHAR(50) DEFAULT NULL,
    pass VARCHAR(50) DEFAULT NULL,
    added_in DATE,
    PRIMARY KEY (id)
    )"""

SELECT_ALL_FROM_EMAILS = "SELECT * FROM emails"

