# -*- coding: utf-8 -*-

# Database implementation generated from reading ui file 'connect_to_database.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mysql.connector import connect, Error
from manage_database import Ui_ManageDatabase

class Ui_Database(object):
    def setupUi(self, Database):
        Database.setObjectName("Database")
        Database.resize(246, 108)
        Database.setMinimumSize(QtCore.QSize(246, 108))
        Database.setMaximumSize(QtCore.QSize(246, 108))
        self.verticalLayout = QtWidgets.QVBoxLayout(Database)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dbNameLabel = QtWidgets.QLabel(Database)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbNameLabel.sizePolicy().hasHeightForWidth())
        self.dbNameLabel.setSizePolicy(sizePolicy)
        self.dbNameLabel.setObjectName("dbNameLabel")
        self.horizontalLayout.addWidget(self.dbNameLabel)
        self.dbNameLineEdit = QtWidgets.QLineEdit(Database)
        self.dbNameLineEdit.setObjectName("dbNameLineEdit")
        self.horizontalLayout.addWidget(self.dbNameLineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connectDbButton = QtWidgets.QPushButton(Database)
        self.connectDbButton.setObjectName("connectDbButton")
        self.connectDbButton.clicked.connect(self.connect_database)
        self.horizontalLayout_2.addWidget(self.connectDbButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.manageDbButton = QtWidgets.QPushButton(Database)
        self.manageDbButton.setObjectName("manageDbButton")
        self.manageDbButton.clicked.connect(self.open_manage_db)
        self.horizontalLayout_2.addWidget(self.manageDbButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.errorStatusLabel = QtWidgets.QLabel(Database)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.errorStatusLabel.sizePolicy().hasHeightForWidth())
        self.errorStatusLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.errorStatusLabel.setFont(font)
        self.errorStatusLabel.setText("")
        self.errorStatusLabel.setObjectName("errorStatusLabel")
        self.verticalLayout.addWidget(self.errorStatusLabel)

        self.retranslateUi(Database)
        QtCore.QMetaObject.connectSlotsByName(Database)

    def retranslateUi(self, Database):
        _translate = QtCore.QCoreApplication.translate
        Database.setWindowTitle(_translate("Database", "Database"))
        self.dbNameLabel.setText(_translate("Database", "Database name:"))
        self.connectDbButton.setText(_translate("Database", "Connect to database"))
        self.manageDbButton.setText(_translate("Database", "Manage database"))

    def open_manage_db(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_ManageDatabase()
        self.ui.setupUi(self.window)
        self.window.show()

    def connect_database(self):
        try:
            if self.dbNameLineEdit.text() == "":
                self.errorStatusLabel.setText("Type a valid name.")

            else:
                connection = connect(
                        host="localhost",
                        user="root",
                        database=self.dbNameLineEdit.text())
                database_name = self.dbNameLineEdit.text()
                self.errorStatusLabel.setText("Connection executed.".format(database_name))
            
        except Error as err:
            self.errorStatusLabel.setText("Connection failed.")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Database = QtWidgets.QWidget()
    ui = Ui_Database()
    ui.setupUi(Database)
    Database.show()
    sys.exit(app.exec_())
