# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'database.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from mysql.connector import connect, Error

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(557, 308)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dbName = QtWidgets.QLabel(Form)
        self.dbName.setObjectName("dbName")
        self.verticalLayout_2.addWidget(self.dbName)
        self.databaseEdit = QtWidgets.QLineEdit(Form)
        self.databaseEdit.setObjectName("databaseEdit")
        self.verticalLayout_2.addWidget(self.databaseEdit)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.passwordEdit = QtWidgets.QLineEdit(Form)
        self.passwordEdit.setObjectName("passwordEdit")
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout_2.addWidget(self.passwordEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonCreateDb = QtWidgets.QPushButton(Form)
        self.pushButtonCreateDb.setObjectName("pushButtonCreateDb")
        self.pushButtonCreateDb.clicked.connect(self.create_database)
        self.horizontalLayout_2.addWidget(self.pushButtonCreateDb)
        self.pushButtonDbConnection = QtWidgets.QPushButton(Form)
        self.pushButtonDbConnection.setObjectName("pushButtonDbConnection")
        self.pushButtonDbConnection.clicked.connect(self.db_connect)
        self.horizontalLayout_2.addWidget(self.pushButtonDbConnection)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dbName.setText(_translate("Form", "Database name"))
        self.label.setText(_translate("Form", "Password"))
        self.pushButtonCreateDb.setText(_translate("Form", "Create Databse"))
        self.pushButtonDbConnection.setText(_translate("Form", "Database Connection"))

    def create_database(self):
        try:
            connection = connect(
                    host="localhost",
                    user="root")
            database_name = self.databaseEdit.text()
            cur = connection.cursor()
            cur.execute("CREATE DATABASE {}".format(database_name))
            self.label_2.setText("Database {} created".format(database_name))
        
        except Error as err:
            print("Database creation failed.")

    def db_connect(self):
        try:
            connection = connect(
                    host="localhost",
                    user="root",
                    database=self.databaseEdit.text())
            database_name = self.databaseEdit.text()
            self.label_2.setText("Connection with {} estabilished.".format(database_name))

        except Error as err:
            self.label_2.setText("Database connection failed.")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
