# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_database.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# TODO: Add button to insert emails and passwords
# TODO: Add button to fetch already added emails
# TODO: Add button to remove emails and passwords



from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ManageDatabase(object):
    def setupUi(self, ManageDatabase):
        ManageDatabase.setObjectName("ManageDatabase")
        ManageDatabase.resize(400, 300)

        self.retranslateUi(ManageDatabase)
        QtCore.QMetaObject.connectSlotsByName(ManageDatabase)

    def retranslateUi(self, ManageDatabase):
        _translate = QtCore.QCoreApplication.translate
        ManageDatabase.setWindowTitle(_translate("ManageDatabase", "Manage database"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManageDatabase = QtWidgets.QWidget()
    ui = Ui_ManageDatabase()
    ui.setupUi(ManageDatabase)
    ManageDatabase.show()
    sys.exit(app.exec_())
